### ISSUE TITLE
Add Group support to library?

### ISSUE THREAD

**Issue by Apollon77** [stfnhmplr/homee-api#1]
I have a request to also support groups (read, control) in the ioBroker adapter 

https://github.com/Apollon77/ioBroker.homee/issues/11

Do you see a way to provide the data and methods for this?

Thank you.

**Comment by stfnhmplr** [comment]
I added some methods to retrieve groups, nodes by group and to create groups.
see #2ea07a1

**Comment by Apollon77** [comment]
Thank you!

Do groups have "a value" (read) or is it possible to set "the value" of the group?

**Comment by stfnhmplr** [comment]
No, it seems theres no function for that. It looks like each switch has to be switched manually.
Maybe I can write a function that switches devices of the same type within a group. Does that make sense and would it help?

**Comment by Apollon77** [comment]
Hm ... could you control all of those devices in one call? Then it would be a benefit. If you do one call for each device then /to be honest) not really interesting in my eyes. But thank you for the offer!
To also be honest: With all these infos I'm not sure If I see a benefit in implementing this at all in the adapter because then groups/scenes in iobroker are the same

**Comment by stfnhmplr** [comment]
No, it looks like that's not possible. I would have to control each device. Then we leave it at the previous functions for groups.

**Comment by Apollon77** [comment]
yes thank you! I think then we can close here
